
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  type: NodePort  # Can be LoadBalancer for cloud environments
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30500  # Exposes AMQP port on NodePort
    - name: management
      port: 15672
      targetPort: 15672  # Management UI Port
      nodePort: 30501
